# This is a TOML document.

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
# First class dates
dob = 1979-05-27T07:32:00-08:00

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true

# Comments on sections are put on top of the section
[servers]
[servers.alpha]
ip = "10.0.0.1"
dc = "eqdc10"

[servers.beta]
ip = "10.0.0.2"
dc = "eqdc10"

[clients]
data = [ [ "gamma", "delta" ], [ 1, 2 ] ]
hosts = [ "alpha", "omega" ]
