regex2 = '''I [dw]on't need \d{2} apples'''
lines = '''The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.'''
quot15 = '''Here are fifteen quotation marks: """""""""""""""'''
str = ''''That,' she said, 'is still pointless.''''
